Repository utmstack/UTMStack, pull requests merged in 2024-01, with the labels that each got.

#223 Refactoring the way that the alert for data sources down is created
  backend/src/main/java/com/park/utmstack/domain/network_scan/wrapper/NetworkScanWrapper.java
  backend/src/main/java/com/park/utmstack/service/UtmDataInputStatusService.java
  backend/src/main/java/com/park/utmstack/service/elasticsearch/ElasticsearchService.java
Labels: bug

#224 Updated the version of the opensearch-connector dependency to 1.0.1
  backend/pom.xml
Labels: bug

#237 A new validation is now in place for saving application configurations regarding the activation of MFA
  backend/src/main/java/com/park/utmstack/service/UtmConfigurationParameterService.java
  backend/src/main/java/com/park/utmstack/util/UtilResponse.java
  backend/src/main/java/com/park/utmstack/util/exceptions/UtmMailException.java
  backend/src/main/java/com/park/utmstack/web/rest/UtmConfigurationParameterResource.java
Labels: bug

#250 Implementing a 404 response code for resource /api/elasticsearch/property/values
  backend/src/main/java/com/park/utmstack/service/elasticsearch/ElasticsearchService.java
  backend/src/main/java/com/park/utmstack/util/UtilResponse.java
  backend/src/main/java/com/park/utmstack/util/exceptions/OpenSearchIndexNotFoundException.java
  backend/src/main/java/com/park/utmstack/web/rest/elasticsearch/ElasticsearchResource.java
Labels: bug

#252 Setting the configuration parameters utmstack.mail.username and utmstack.mail.password as not required.
  backend/src/main/resources/config/liquibase/changelog/20240109001_modifying_requirement_for_configuration_parameters.xml
  backend/src/main/resources/config/liquibase/master.xml
Labels: bug, enhancement

#246 Feature/v10.2/user auditor change scan interval
  user-auditor/src/main/java/com/utmstack/userauditor/model/SourceScan.java
  user-auditor/src/main/java/com/utmstack/userauditor/service/Impl/WindowsSource.java
  user-auditor/src/main/java/com/utmstack/userauditor/service/UserService.java
  user-auditor/src/main/resources/db/changelog/changes/002-2024-01-09-change-next-execution-date.sql
  user-auditor/src/main/resources/db/changelog/db.changelog-master.yaml
Labels: bug

#265 Escaping OpenSearch reserved characters for the query_string query
  backend/src/main/java/com/park/utmstack/service/elasticsearch/SearchUtil.java
  backend/src/main/java/com/park/utmstack/util/CustomStringEscapeUtil.java
Labels: bug

#298 Optimizing code and dependencies (296)
  user-auditor/pom.xml
Labels: dependencies

#335 Fixing overwriting of the properties host and IP of the alert that is created for a data source down
  backend/src/main/java/com/park/utmstack/service/UtmDataInputStatusService.java
Labels: bug

#347 Fixing overwriting of the properties host and IP of the alert that is created for a data source down
  backend/src/main/java/com/park/utmstack/service/UtmDataInputStatusService.java
Labels: bug

#339 Adding selenium and pdf services to installer
  installer/compose.go
Labels: enhancement
